export const APP_SET_PATH = "APP_SET_PATH";

export const LOGIN_INPUT_CHANGED_HANDLER = "LOGIN_INPUT_CHANGED_HANDLER";
export const LOGIN_SUBMIT = "LOGIN_SUBMIT";

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH";

//export const FORGOT_PASSWORD = "FORGOT_PASSWORD";
export const FORGOT_START = "FORGOT_START";
export const FORGOT_FAIL = "FORGOT_FAIL";
export const FORGOT_SUCCESS = "FORGOT_SUCCESS";


export const USERS_REQUEST_START = "USERS_REQUEST_START";
export const USERS_REQUEST_FAIL = "USERS_REQUEST_FAIL";
export const USERS_REQUEST_SUCCESS = "USERS_REQUEST_SUCCESS";

export const OPEN_CHALLENGES_REQUEST_START = "OPEN_CHALLENGES_REQUEST_START";
export const OPEN_CHALLENGES_REQUEST_FAIL = "OPEN_CHALLENGES_REQUEST_FAIL";
export const OPEN_CHALLENGES_REQUEST_SUCCESS = "OPEN_CHALLENGES_REQUEST_SUCCESS";

export const MATCH_PLAYED_REQUEST_START = "MATCH_PLAYED_REQUEST_START";
export const MATCH_PLAYED_REQUEST_FAIL = "MATCH_PLAYED_REQUEST_FAIL";
export const MATCH_PLAYED_REQUEST_SUCCESS = "MATCH_PLAYED_REQUEST_SUCCESS";

export const OPEN_CONTENT_REQUEST_START = "OPEN_CONTENT_REQUEST_START";
export const OPEN_CONTENT_REQUEST_FAIL = "OPEN_CONTENT_REQUEST_FAIL";
export const OPEN_CONTENT_REQUEST_SUCCESS = "OPEN_CONTENT_REQUEST_SUCCESS";
export const GET_CONTENT_BY_SLUG = "GET_CONTENT_BY_SLUG";
export const UPDATE_CONTENT_REQUEST = "UPDATE_CONTENT_REQUEST";


